[/Script/UnrealEd.EditorEngine]
; Prefer One File Per Actor for multiplayer-friendly level collaboration.
bEnableWorldPartition=True

[/Script/UnrealEd.LevelEditorPlaySettings]
GameGetsMouseControl=True
UseMouseForTouch=False
EnableGameSound=True
NetworkEmulationSettings=(bIsNetworkEmulationEnabled=False)
